---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
        files: "(^roles/.*|galaxy|main|requirements|runtime)\\.yml$"
        exclude: (^.github/|^.pre-commit-config\\.yaml$)
  - repo: https://github.com/ansible-community/ansible-lint.git
    # https://github.com/ansible-community/ansible-lint/releases/
    rev: v6.21.1
    hooks:
      - id: ansible-lint
        always_run: false
        files: "(^roles/.*|galaxy|main|requirements|runtime)\\.yml$"
