---
- name: Setup laptop environment
  hosts: localhost
  vars:
    git_workspaces:
      - name: "github_work"
        path: "{{ lookup('env', 'HOME') }}/Workspace"
        ssh:
          signature:
            private_key: "private_key"
            public_key: "public_key"
            allowed_signers: "{{ lookup('env', 'HOME') }}/.ssh/allowed_signers"
          authentication:
            public_key: "public_key"
        user_name: "user_name"
        user_email: "user_email"
      - name: "github_personal"
        path: "{{ lookup('env', 'HOME') }}/Github"
        ssh:
          signature:
            program: /Applications/1Password.app/Contents/MacOS/op-ssh-sign
            public_key: "public_key"
            allowed_signers: "{{ lookup('env', 'HOME') }}/.ssh/allowed_signers"
          authentication:
            public_key: "public_key"
        user_name: "user_name"
        user_email: "user_email"
    dock_items: [] # ci fails because of adding elements not working as expected
  roles:
    - applications
    - customization
