name: "Setup the environment"
description: "action to setup the environment"
runs:
  using: "composite"
  steps:
    - name: Set up Python 3
      uses: actions/setup-python@v3
    - name: Install python dependencies
      shell: bash
      run: pip3 install ansible
    - name: Install ansible collections.
      shell: bash
      run: |
        ansible-galaxy install -r requirements.yml
