---
- name: Install packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ packages | flatten(levels=1) }}"

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ cask | flatten(levels=1) }}"

- name: Install Mac App Store apps
  community.general.mas:
    id: "{{ item.1.id }}"
    state: present
  loop: "{{ app_store_apps | subelements('items') }}"
