---
- name: Check Homebrew is installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:
    - not homebrew_check.stat.exists
  changed_when: false

- name: Install packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ packages | flatten(levels=1) }}"
  changed_when: false

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ cask | flatten(levels=1) }}"
  changed_when: false

- name: Install Mac App Store apps
  community.general.mas:
    id: "{{ item.1.id }}"
    state: present
  loop: "{{ app_store_apps | subelements('items') }}"
  changed_when: false
