---
- name: Install applications with brew
  ansible.builtin.import_tasks: brew.yml

- name: Setup java
  ansible.builtin.import_tasks: java.yml

- name: Setup node
  ansible.builtin.import_tasks: node.yml

- name: Setup python
  ansible.builtin.import_tasks: python.yml
