---
- name: Check Homebrew is installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Download Homebrew
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew.sh
    mode: u=rwx,g=rx,o=r
    when: not homebrew_check.stat.exists

- name: Install Homebrew
  ansible.builtin.script: /tmp/homebrew.sh
  when:
    - not homebrew_check.stat.exists

- name: Install packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ packages | flatten(levels=1) }}"

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ cask | flatten(levels=1) }}"

- name: Install Mac App Store apps
  community.general.mas:
    id: "{{ item.1.id }}"
    state: present
  loop: "{{ app_store_apps | subelements('items') }}"
