---
- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install packages from cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask }}"

- name: Install Mac App Store apps
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  with_items: "{{ app_store_apps }}"