---
- name: Set nvm_init variable
  ansible.builtin.set_fact:
    nvm_init:
      export PATH="$PATH:/usr/local/bin:/opt/homebrew/bin" && export
      NVM_DIR="$HOME/.nvm" && source "$(brew --prefix)/opt/nvm/nvm.sh"

- name: Install latest node via nvm
  ansible.builtin.shell:
    "{{ nvm_init }} && nvm install --skip-default-packages --default node"
  register: nvm_install_latest_node
  args:
    executable: /bin/zsh
  changed_when: not nvm_install_latest_node.stdout.find("is already installed")
  failed_when: nvm_install_latest_node.rc != 0

- name: Verify pnpm is installed via nvm exec
  ansible.builtin.shell: "{{ nvm_init }} && nvm exec pnpm --version"
  args:
    executable: /bin/zsh
  register: pnpm_version
  changed_when: false
  failed_when: false

- name: Install pnpm via nvm
  ansible.builtin.shell: "{{ nvm_init }} && nvm exec npm install -g pnpm"
  args:
    executable: /bin/zsh
  register: pnpm_installation
  when: pnpm_version.rc != 0
  changed_when: true
  failed_when: pnpm_installation.rc != 0
