---
galaxy_info:
  author: andrea11
  description: Install latest python version using pyenv
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - applications
    - customization
    - macos
dependencies:
  - role: andrea11.macos_setup.install_applications
    vars:
      install_applications_formulae:
        - pyenv
        - pyenv-virtualenv
