---
- name: Install dockutil
  community.general.homebrew_cask:
    name: "dockutil"
    state: present

- name: Remove all dock items
  # ansible.builtin.command: "dockutil --remove all --no-restart"
  ansible.builtin.command: "dockutil --remove all"
  register: removed_items_task
  changed_when: false
  # notify:
  #   - clear_dock_cache
  #   - restart_dock

- name: Add all dock items
  ansible.builtin.command: "dockutil --add '{{ item.path }}' --position {{ item.position }}"
  changed_when: false
  loop: "{{ dock_items | flatten(levels=1) }}"
  when: (item.name ~ " was not found in") in item.stdout
