---
- name: Install dockutil
  community.general.homebrew_cask:
    name: dockutil
    state: present

- name: Get dock items
  ansible.builtin.command: dockutil --list
  register: get_dock_items_task
  changed_when: false
  failed_when: get_dock_items_task.rc != 0

- name: Extract persistent dock item names
  ansible.builtin.set_fact:
    all_persistant_dock_item_names: "{{ all_persistant_dock_item_names | default([]) |
      union([get_dock_items_task.stdout_lines | select('search', 'persistentApps') |
      map('regex_replace', '^(.*?)\\t.*', '\\1')]) | flatten }}"
  loop: "{{ dock_items }}"

- name: Check if all desired dock items are present
  ansible.builtin.set_fact:
    all_items_present: "{{ dock_items | map(attribute='name') | difference(all_persistant_dock_item_names) | length == 0 }}"

- name: Debug dock items
  ansible.builtin.debug:
    msg:
      - "get_dock_items_task: {{ get_dock_items_task }}"
      - "all_persistant_dock_item_names: {{ all_persistant_dock_item_names }}"
      - "all_items_present: {{ all_items_present }}"
      - "{{ lookup('pipe', 'dockutil --list') }}"

- name: Remove all dock items
  ansible.builtin.command: dockutil --remove all
  register: remove_all_dock_items_task
  when: not all_items_present
  changed_when: get_dock_items_task.stdout != lookup('pipe', 'dockutil --list')
  failed_when: remove_all_dock_items_task.rc != 0

- name: Add all dock items
  ansible.builtin.command: dockutil --add '{{ item.path }}' --position {{ item.position }}
  loop: "{{ dock_items }}"
  changed_when: '"{} already exists in dock".format(item.name) not in add_all_dock_items_task_result.stdout'
  register: add_all_dock_items_task_result
  failed_when:
    - add_all_dock_items_task_result.rc != 0
    - '"{} already exists in dock".format(item.name) not in add_all_dock_items_task_result.stdout'

- name: Debug all dock items
  ansible.builtin.debug:
    msg:
      - "get_dock_items_task: {{ get_dock_items_task }}"
      - "all_persistant_dock_item_names: {{ all_persistant_dock_item_names }}"
      - "all_items_present: {{ all_items_present }}"
      - "{{ lookup('pipe', 'dockutil --list') }}"
