---
- name: Verify if finicky is configured
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.finicky.js"
  register: finicky_check

- name: Setup finicky if not yet configured
  ansible.builtin.file:
    src: "{{ role_path }}/templates/.finicky.js"
    dest: "{{ lookup('env', 'HOME') }}/.finicky.js"
    state: hard
    mode: u=rw,g=rw,o=r
  when: not finicky_check.stat.exists
