---
- name: Get all applications installed
  ansible.builtin.find:
    paths: /Applications
    patterns: "*.app"
    file_type: any
  register: applications

- name: Get all last used date for installed applications
  ansible.builtin.command: "mdls '{{ item }}' -name kMDItemLastUsedDate"
  loop: "{{ applications.files | map(attribute='path') }}"
  register: applications_last_used_date
  changed_when: false

- name: Get all applications installed never opened before
  ansible.builtin.set_fact:
    applications_never_opened: "{{ applications_never_opened | default([]) | union([item.item]) }}"
  loop: "{{ applications_last_used_date.results }}"
  when: item.stdout == "kMDItemLastUsedDate = (null)"

- name: Open all applications for the first time
  ansible.builtin.command: open -a "{{ item }}"
  loop: "{{ applications_never_opened }}"
  when: applications_never_opened is defined
  changed_when: false
  failed_when: false
