---
- name: Generate .gitconfig file
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    mode: u=rw,g=rw,o=r

- name: Create workspace folder if not exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: u=xrw,g=xr,o=x
  loop: "{{ git_workspaces }}"

- name: Generate .gitconfig file per each workspace
  ansible.builtin.template:
    src: .gitconfig_workspace.j2
    dest: "{{ item.path }}/.gitconfig"
    mode: u=rw,g=rw,o=r
  loop: "{{ git_workspaces }}"
  vars:
    user_name: "{{ item.user_name }}"
    user_email: "{{ item.user_email }}"
    workspace_name: "{{ item.name }}"
    ssh:
      signature:
        public_key: "{{ item.ssh.signature.public_key }}"
        program: "{{ item.ssh.signature.program | default('') }}"
        allowed_signers: "{{ item.ssh.signature.allowed_signers }}"
        public_key_path: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.name }}_signature_ed25519.pub"
