---
- name: Generate .gitconfig file
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: $HOME/.gitconfig
    mode: u=rw,g=rw,o=r
  vars:
    workspaces: "{{ git_workspaces | map(attribute='path') }}"

- name: Generate .gitconfig file per each workspace
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: $HOME/.gitconfig.{{ item }}
    mode: u=rw,g=rw,o=r
  loop: "{{ git_workspaces }}"
  vars:
    user_name: "{{ item.user_name }}"
    user_email: "{{ item.user_email }}"
