---
- name: Set macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  loop: "{{ macos_defaults | flatten(levels=1) }}"

- name: Setup Dock icons
  ansible.builtin.include_tasks: dock.yml

- name: Set up .zshrc
  ansible.builtin.copy:
    src: files/.zshrc
    dest: ~/.zshrc
    mode: u=rw,g=rw,o=r
