---
- name: Setup Dock icons
  ansible.builtin.import_tasks: dock.yml

- name: Set macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  loop: "{{ macos_defaults }}"

- name: Setup terminal
  ansible.builtin.import_tasks: terminal.yml

# - name: Setup git
#   ansible.builtin.include_tasks: git.yml
