---
- name: Setup applications for the first time
  ansible.builtin.import_tasks: first_setup.yml

- name: Setup Dock icons
  ansible.builtin.import_tasks: dock.yml

- name: Set macOS defaults
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  loop: "{{ macos_defaults }}"

- name: Setup terminal
  ansible.builtin.import_tasks: terminal.yml

- name: Setup git
  ansible.builtin.import_tasks: git.yml

- name: Setup ssh
  ansible.builtin.import_tasks: ssh.yml

- name: Setup finicky
  ansible.builtin.import_tasks: finicky.yml
