---
- name: Create ssh folder if not exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: u=xrw,go=

- name: Generate ssh config file per each workspace
  ansible.builtin.template:
    src: git_ssh_config.j2
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.name }}_config"
    mode: u=rw,go=
  loop: "{{ git_workspaces }}"
  vars:
    identity_file_path: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.name }}_authentication_ed25519.pub"

- name: Create allowed_signers parent folders if not exist
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    mode: u=xrw,go=
  loop: "{{ git_workspaces | map(attribute='ssh') | map(attribute='signature') | map(attribute='allowed_signers') | unique }}"

- name: Add allowed_signer to allowed_signers file if needed
  ansible.builtin.lineinfile:
    path: "{{ item.ssh.signature.allowed_signers }}"
    line: "{{ item.user_email }} {{ item.ssh.signature.public_key }}"
    regexp: "^{{ item.user_email | ansible.builtin.regex_escape }} {{ item.ssh.signature.public_key | ansible.builtin.regex_escape }}$"
    state: present
    create: true
    mode: u=rw,go=r
  loop: "{{ git_workspaces }}"

- name: Generate authentication public ssh key files per each workspace
  ansible.builtin.copy:
    content: "{{ item.ssh.authentication.public_key }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.name }}_authentication_ed25519.pub"
    mode: u=rw,go=r
  loop: "{{ git_workspaces }}"

- name: Generate signature public ssh key files per each workspace
  ansible.builtin.copy:
    content: "{{ item.ssh.signature.public_key }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.name }}_signature_ed25519.pub"
    mode: u=rw,go=r
  loop: "{{ git_workspaces }}"

- name: Generate signature private ssh key files per each workspace
  ansible.builtin.copy:
    content: "{{ item.ssh.signature.private_key }}"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item.name }}_signature_ed25519"
    mode: u=rw,go=
  when: item.ssh.signature.private_key is defined
  loop: "{{ git_workspaces }}"
