---
- name: Set up .zshrc
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: u=rw,g=r,o=r
    checksum: sha1
  with_fileglob:
    - templates/.zshrc
    - templates/.aliases
  tags:
    - test
  notify: Reload .zshrc
