---
- name: Set terminal_init variable
  ansible.builtin.set_fact:
    terminal_init: "source {{ lookup('env', 'HOME') }}/.zshrc"

- name: Install latest node via nvm
  ansible.builtin.shell:
    "{{ terminal_init }} && nvm install --skip-default-packages --default node"
  register: nvm_install_latest_node
  args:
    executable: /bin/zsh
  changed_when: not nvm_install_latest_node.stdout.find("is already installed")
  failed_when: nvm_install_latest_node.rc != 0

- name: Verify pnpm is installed via nvm exec
  ansible.builtin.shell:
    "{{ terminal_init }} && nvm exec pnpm --version"
  args:
    executable: /bin/zsh
  register: pnpm_version
  changed_when: false
  failed_when: false

- name: Install pnpm via nvm
  ansible.builtin.shell:
    "{{ terminal_init }} && nvm exec npm install -g pnpm"
  args:
    executable: /bin/zsh
  register: pnpm_installation
  when: pnpm_version.rc != 0
  changed_when: true
  failed_when: pnpm_installation.rc != 0
