---
galaxy_info:
  author: andrea11
  description:
    Finicky is a macOS application that allows you to set up rules that
    decide which browser is opened for every link. This role configures finicky
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - application
    - finicky
    - browser
    - customization
    - macos
dependencies:
  - role: andrea11.macos_setup.install_applications
    vars:
      install_applications_casks:
        - finicky
