---
packages:
  - docker-compose
  - geckodriver
  - gnupg
  - jq
  - libfido2
  - nvm
  - openssh
  - pinentry-mac
  - pre-commit
  - pyenv
  - pyenv-virtualenv
  - protobuf
  - sdkman-cli
  - watch
  - wget
  - ykman
  - zoxide
casks:
  - 1password
  - 1password-cli
  - awscli
  - aws-vault
  - chromedriver
  - finicky
  - firefox
  - font-fira-code
  - hpedrorodrigues/tools/dockutil
  - hush
  - intellij-idea
  - microsoft-edge
  - orbstack
  - rectangle
  - spotify
  - visual-studio-code
  - warp
  - whatsapp
taps:
  - homebrew/cask-fonts
  - sdkman/tap
java_major_versions:
  - 11
  - 17
certificate_websites:
  - url: artifactory.intra.nexthink.com
    port: 443
    alias: "Nexthink Artifactory"
