---
galaxy_info:
  author: andrea11
  description: Customize the macOS defaults
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - applications
    - defaults
    - macos
    - customization
dependencies: []
