---
- name: Set macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
    host: "andrea.accardo"
  loop: "{{ customize_defaults_settings }}"
