---
galaxy_info:
  author: andrea11
  description:
    It configures ssh. Different ssh accounts can be configured in different
    workspaces. This is useful if you have multiple ssh accounts
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - applications
    - customization
    - macos
dependencies: []
