---
- name: Check if brew is installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew_installed

- name: Install Homebrew
  become: true
  ansible.builtin.shell:
    /bin/bash -c "$(curl -fsSL
    https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
    creates: /usr/local/bin/brew
  when: not brew_installed.stat.exists

- name: Install taps
  community.general.homebrew_tap:
    name: "{{ install_applications_taps }}"
    state: present
  when: install_applications_taps | length > 0

- name: Install packages via formulae
  community.general.homebrew:
    name: "{{ install_applications_formulae }}"
    state: present
  when: install_applications_formulae | length > 0

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ install_applications_casks }}"
    state: present
  when: install_applications_casks | length > 0
