---
- name: Check if brew is installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew_installed

- name: Download Homebrew
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew.sh
    mode: u=rwx,g=rx,o=r
  when: not brew_installed.stat.exists

- name: Install Homebrew
  become: true
  ansible.builtin.script: /tmp/homebrew.sh
  args:
    creates: /usr/local/bin/brew
  when: not brew_installed.stat.exists

- name: Install taps
  community.general.homebrew_tap:
    name: "{{ install_applications_taps }}"
    state: present
  when: install_applications_taps | length > 0

- name: Install packages via formulae
  community.general.homebrew:
    name: "{{ install_applications_formulae }}"
    state: present
  when: install_applications_formulae | length > 0

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ install_applications_casks }}"
    state: present
  when: install_applications_casks | length > 0
