---
- name: Check if brew is installed
  community.general.homebrew:
    update_homebrew: true
  check_mode: true
  failed_when: false
  register: brew_installed

- name: Install Homebrew
  ansible.builtin.shell:
    /bin/bash -c "$(curl -fsSL
    https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" <
    /dev/null
  args:
    creates: /usr/local/bin/brew
  when: brew_installed is failed

- name: Install taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ install_applications_taps }}"

- name: Install packages via formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ install_applications_formulae }}"

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ sudo_password | default(omit) }}"
  loop: "{{ install_applications_casks }}"
