---
- name: Set brew_init variable
  ansible.builtin.set_fact:
    brew_init: export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"

- name: Check if brew is installed
  ansible.builtin.shell: "{{ brew_init }} && brew --version"
  ignore_errors: true
  changed_when: false
  register: brew_installed

- name: Install Homebrew
  ansible.builtin.shell:
    /bin/bash -c "$(curl -fsSL
    https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" <
    /dev/null
  args:
    creates: /usr/local/bin/brew
  when: brew_installed.rc != 0

- name: Install taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ install_applications_taps }}"

- name: Install packages via formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ install_applications_formulae }}"

- name: Install packages from cask
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ sudo_password | default(omit) }}"
  loop: "{{ install_applications_casks }}"
